### ISSUE TITLE
Linux 安装注意事项

### ISSUE THREAD

**Issue by Rainflown** [gpzlx1/HowToInstallVivado#1]
根据安装时提示,参考 [ug973-vivado-release-notes-install-license.pdf](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2018_1/ug973-vivado-release-notes-install-license.pdf) 中28页 Installing Cable Drivers

> For Linux, because root or sudo access is required to install drivers, this option has been removed from the Linux installer beginning in Vivado 2015.4. The general Vivado installer can now be run on Linux without root or sudo privileges. To install cable drivers on Linux, there is now a script that must be run as root or sudo post installation.
> **Script Location**: `<Vivado Install Dir>/data/xicom/cable_drivers/lin64/install_script/install_drivers/`
> **Script Name**: `install_drivers`

**Comment by gpzlx1** [comment]
https://github.com/gpzlx1/HowToInstallVivado/blob/master/How_to_Install_vivado_for_linux.md 参考安装
